# filepath: skills/devops/nginx-conf/worker.py
import logging
from skillforge.base import BaseWorker, SkillInput, SkillOutput

logger = logging.getLogger(__name__)

class Worker(BaseWorker):
    """Generate nginx configuration."""
    skill_id = "devops.nginx-conf"
    version = "1.0.0"

    def run(self, input: SkillInput) -> SkillOutput:
        try:
            domains: list = input.data.get("domains", [])
            if not domains:
                return SkillOutput(success=False, error="'domains' is required.")
            ssl: bool = input.data.get("use_ssl", True)
            rate: bool = input.data.get("rate_limiting", False)
            gzip: bool = input.data.get("gzip", True)
            headers: bool = input.data.get("add_security_headers", True)

            parts = ["# Auto-generated by SkillForge"]
            if rate:
                parts.append("limit_req_zone $binary_remote_addr zone=api:10m rate=60r/m;")
            if gzip:
                parts.append("gzip on;\ngzip_types text/plain application/json text/css;")

            snippets: dict[str, str] = {}
            certbot_cmds: list[str] = []

            if headers:
                sec = "add_header X-Frame-Options DENY;\nadd_header X-Content-Type-Options nosniff;\nadd_header Referrer-Policy strict-origin;\n"
                snippets["security_headers.conf"] = sec

            for d in domains:
                sn = d.get("server_name", "localhost")
                port = d.get("upstream_port", 8000)
                parts.append(f"\nserver {{")
                if ssl:
                    parts.append(f"  listen 443 ssl;")
                    parts.append(f"  ssl_certificate /etc/letsencrypt/live/{sn}/fullchain.pem;")
                    parts.append(f"  ssl_certificate_key /etc/letsencrypt/live/{sn}/privkey.pem;")
                    certbot_cmds.append(f"certbot --nginx -d {sn}")
                else:
                    parts.append(f"  listen 80;")
                parts.append(f"  server_name {sn};")
                if headers:
                    parts.append(f"  include /etc/nginx/snippets/security_headers.conf;")
                if rate:
                    parts.append(f"  limit_req zone=api burst=20 nodelay;")
                parts.append(f"  location / {{")
                parts.append(f"    proxy_pass http://127.0.0.1:{port};")
                parts.append(f"    proxy_set_header Host $host;")
                parts.append(f"    proxy_set_header X-Real-IP $remote_addr;")
                parts.append(f"  }}")
                parts.append(f"}}")

                if ssl and d.get("www_redirect", False):
                    parts.append(f"\nserver {{\n  listen 80;\n  server_name {sn} www.{sn};\n  return 301 https://{sn}$request_uri;\n}}")

            return SkillOutput(success=True, data={
                "nginx_conf": "\n".join(parts), "snippets": snippets,
                "certbot_commands": certbot_cmds, "test_command": "nginx -t",
            }, metadata={"skill_id": self.skill_id})
        except Exception as e:
            return SkillOutput(success=False, error=str(e))
